apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: zipbw228k-go-gitops
  description: This is GitOps manifest for zipbw228k-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: zipbw228k-go
    backstage.io/kubernetes-id: zipbw228k-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: zipbw228k-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:zipbw228k-go
